from main import run_analysis
from main import ResultsData
from mesh.mesh import MeshData
from fixtures import base_case_study, base_case_study_2, base_case_study_3
import matplotlib.pyplot as plt

'''def test_base_case(base_case_study) -> None:
    results = run_analysis(base_case_study)

    plt.plot(results.Tvec, results.Pvec,label='P vs T')
    plt.xlabel('Temperature(K)')
    plt.ylabel('Pressure(Bar)')
    plt.title('Perfil Termohidráulico')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Pvec, label='Pressure vs MD')
    plt.xlabel('MD')
    plt.ylabel('Pressure')
    plt.title('Pressure vs MD')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Tvec, label='Temperature vs MD')
    plt.xlabel('MD')
    plt.ylabel('Temperature')
    plt.title('Temperature vs MD')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Pb_vec, label='Pb vs MD')
    plt.xlabel('MD')
    plt.ylabel('Pb')
    plt.title('Pressão de bolha vs Comprimento')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Rs_vec, label='Rs vs MD')
    plt.xlabel('MD')
    plt.ylabel('Rs')
    plt.title('Razão de solubilidade vs Comprimento')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Bo_vec, label='Bo vs MD')
    plt.xlabel('MD')
    plt.ylabel('Bo')
    plt.title('Fator volume do óleo vs Comprimento')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_oil_vec, label='ρ_oil vs MD')
    plt.xlabel('MD')
    plt.ylabel('ρ_oil')
    plt.title('Densidade específica do óleo vs Comprimento')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_gas_vec, label='ρ_gas vs MD')
    plt.xlabel('MD')
    plt.ylabel('ρ_gas')
    plt.title('Densidade específica do gás vs Comprimento')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_oil_vec, label='μ_oil vs MD')
    plt.xlabel('MD')
    plt.ylabel('μ_oil')
    plt.title('Viscosidade do óleo vs Comprimento')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_gas_vec, label='μ_gas vs MD')
    plt.xlabel('MD')
    plt.ylabel('μ_gas')
    plt.title('Viscosidade do gás vs Comprimento')
    plt.legend()
    plt.show()
    assert 1 == 1'''''


def test_base_case_2(base_case_study_2) -> None:
    results = run_analysis(base_case_study_2)

    plt.plot(results.Tvec, results.Pvec, label='P vs T')
    plt.xlabel('Temperature(K)')
    plt.ylabel('Pressure(Pa)')
    plt.title('Perfil Termohidráulico- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Pvec, label='P vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('Pressão (Pa)')
    plt.title('Pressão vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Tvec, label='T vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('Temperatura (K)')
    plt.title('Temperatura vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.HLvec, label='HL vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('HL')
    plt.title('Holdup de Líquido vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_slip_vec, label='ρ_slip vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('ρ_slip (Kg/m3)')
    plt.title('Densidade da mistura Slip vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_slip_vec, label='μ_slip vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('μ_slip (Pa.S)')
    plt.title('Viscosidade da Mistura Slip vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Pb_vec, label='Pb vs MD')
    plt.xlabel('MD')
    plt.ylabel('Pb')
    plt.title('Pressão de bolha vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Rs_vec, label='Rs vs MD')
    plt.xlabel('MD')
    plt.ylabel('Rs')
    plt.title('Razão de solubilidade vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Bo_vec, label='Bo vs MD')
    plt.xlabel('MD')
    plt.ylabel('Bo')
    plt.title('Fator volume do óleo vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_oil_vec, label='ρ_oil vs MD')
    plt.xlabel('MD')
    plt.ylabel('ρ_oil')
    plt.title('Densidade específica do óleo vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.ρ_oil_vec, label='ρ_oil vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('ρ_oil')
    plt.title('Densidade específica do óleo vs Pressão- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_gas_vec, label='ρ_gas vs MD')
    plt.xlabel('MD')
    plt.ylabel('ρ_gas')
    plt.title('Densidade específica do gás vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.ρ_gas_vec, label='ρ_gas vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('ρ_gas')
    plt.title('Densidade específica do gás vs Pressão- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_oil_vec, label='μ_oil vs MD')
    plt.xlabel('MD')
    plt.ylabel('μ_oil')
    plt.title('Viscosidade do óleo vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.μ_oil_vec, label='μ_oil vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('μ_oil')
    plt.title('Viscosidade do óleo vs Pressão- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_gas_vec, label='μ_gas vs MD')
    plt.xlabel('MD')
    plt.ylabel('μ_gas')
    plt.title('Viscosidade do gás vs Comprimento- Noruega')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.μ_gas_vec, label='μ_gas vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('μ_gas')
    plt.title('Viscosidade do gás vs Pressão- Noruega')
    plt.legend()
    plt.show()
    assert 1 == 1


def test_base_case_3(base_case_study_3) -> None:
    results = run_analysis(base_case_study_3)

    plt.plot(results.Tvec, results.Pvec, label='P vs T')
    plt.xlabel('Temperature(K)')
    plt.ylabel('Pressure(Pa)')
    plt.title('Perfil Termohidráulico- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Pvec, label='P vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('Pressão (Pa)')
    plt.title('Pressão vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Tvec, label='T vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('Temperatura (K)')
    plt.title('Temperatura vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.HLvec, label='HL vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('HL')
    plt.title('Holdup de Líquido vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_slip_vec, label='ρ_slip vs MD')
    plt.xlabel('MD (m)')
    plt.ylabel('ρ_slip (Kg/m3)')
    plt.title('Densidade da mistura Slip vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_slip_vec, label='μ_slip vs MD')
    plt.xlabel('MD')
    plt.ylabel('μ_slip (Pa.S)')
    plt.title('Viscosidade da Mistura Slip vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Pb_vec, label='Pb vs MD')
    plt.xlabel('MD')
    plt.ylabel('Pb')
    plt.title('Pressão de bolha vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Rs_vec, label='Rs vs MD')
    plt.xlabel('MD')
    plt.ylabel('Rs')
    plt.title('Razão de solubilidade vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.Bo_vec, label='Bo vs MD')
    plt.xlabel('MD')
    plt.ylabel('Bo')
    plt.title('Fator volume do óleo vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_oil_vec, label='ρ_oil vs MD')
    plt.xlabel('MD')
    plt.ylabel('ρ_oil')
    plt.title('Densidade específica do óleo vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.ρ_oil_vec, label='ρ_oil vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('ρ_oil')
    plt.title('Densidade específica do óleo vs Pressão- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.ρ_gas_vec, label='ρ_gas vs MD')
    plt.xlabel('MD')
    plt.ylabel('ρ_gas')
    plt.title('Densidade específica do gás vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.ρ_gas_vec, label='ρ_gas vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('ρ_gas')
    plt.title('Densidade específica do gás vs Pressão- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_oil_vec, label='μ_oil vs MD')
    plt.xlabel('MD')
    plt.ylabel('μ_oil')
    plt.title('Viscosidade do óleo vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.μ_oil_vec, label='μ_oil vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('μ_oil')
    plt.title('Viscosidade do óleo vs Pressão- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.MD, results.μ_gas_vec, label='μ_gas vs MD')
    plt.xlabel('MD')
    plt.ylabel('μ_gas')
    plt.title('Viscosidade do gás vs Comprimento- Venezuela')
    plt.legend()
    plt.show()

    plt.plot(results.Pvec, results.μ_gas_vec, label='μ_gas vs Pvec')
    plt.xlabel('Pvec')
    plt.ylabel('μ_gas')
    plt.title('Viscosidade do gás vs Pressão- Venezuela')
    plt.legend()
    plt.show()
    assert 1 == 1

